global:
  scrape_interval: 1m

remote_write:
  - url: <remote_write_url>
    remote_timeout: 60s
    basic_auth:
      username: <username>
      password: <password>

scrape_configs:
  - job_name: "order-service-mysql"
    static_configs:
      - targets: [ "app:9097" ]
  - job_name: "node-exporter"
    static_configs:
      - targets: [ "app:9100" ]
  - job_name: "prometheus-agent"
    static_configs:
      - targets: ["localhost:9743"]
